# Generated by Django 5.2.9 on 2025-12-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sello_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
