# Generated by Django 5.2.9 on 2025-12-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sello_news', '0003_alter_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение'),
        ),
    ]
