# Generated by Django 4.2.7 on 2025-12-03 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название бренда')),
                ('country', models.CharField(choices=[('Россия', 'Россия'), ('США', 'США'), ('Германия', 'Германия'), ('Китай', 'Китай'), ('Япония', 'Япония'), ('Италия', 'Италия'), ('Франция', 'Франция'), ('Великобритания', 'Великобритания'), ('Южная Корея', 'Южная Корея'), ('Другое', 'Другое')], max_length=50, verbose_name='Страна')),
                ('category', models.CharField(choices=[('Электроника', 'Электроника'), ('Одежда', 'Одежда'), ('Продукты', 'Продукты'), ('Сельхозтехника', 'Сельхозтехника'), ('Строительство', 'Строительство'), ('Красота и здоровье', 'Красота и здоровье'), ('Автомобили', 'Автомобили'), ('Мебель', 'Мебель'), ('Спорт', 'Спорт'), ('Другое', 'Другое')], max_length=50, verbose_name='Категория')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, verbose_name='Описание бренда')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('main_category', models.CharField(max_length=100, verbose_name='Основная категория')),
                ('category', models.CharField(max_length=200, verbose_name='Категория')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='sello_tovar.brand', verbose_name='Бренд')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=100, verbose_name='Основная категория')),
                ('subcategory', models.CharField(max_length=200, verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'unique_together': {('main_category', 'subcategory')},
            },
        ),
    ]
