# Generated by Django 5.2.9 on 2025-12-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sello_tovar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/logos/%Y/%m/%d/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
