# Generated by Django 5.2.9 on 2026-01-14 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(verbose_name='ID проекта в конструкторе')),
                ('title', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url_slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_shop', models.BooleanField(default=False, verbose_name='Это магазин')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('brand', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_project', to='lk.brand', verbose_name='Связанный магазин')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_projects', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Опубликованный проект',
                'verbose_name_plural': 'Опубликованные проекты',
                'db_table': 'published_projects',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['is_active', 'published_at'], name='published_p_is_acti_8d2db8_idx'), models.Index(fields=['owner', 'is_active'], name='published_p_owner_i_57b67c_idx'), models.Index(fields=['category', 'is_active'], name='published_p_categor_fff4e9_idx')],
            },
        ),
    ]
