# Generated by Django 5.2.9 on 2026-01-14 20:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0002_publishedproject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='publishedproject',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userbrandconnection',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='publishedproject',
            name='published_p_is_acti_8d2db8_idx',
        ),
        migrations.RemoveIndex(
            model_name='publishedproject',
            name='published_p_owner_i_57b67c_idx',
        ),
        migrations.RemoveIndex(
            model_name='publishedproject',
            name='published_p_categor_fff4e9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userbrandconnection',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='url_slug',
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='bg_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='blocks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='preview_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='text_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='brand',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lk_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lk_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lk_items', to='lk.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lk.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='lk.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='is_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userbrandconnection',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_users', to='lk.brand'),
        ),
        migrations.AlterField(
            model_name='userbrandconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='brand',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='publishedproject',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userbrandconnection',
            table=None,
        ),
    ]
