# Generated by Django 5.2.9 on 2026-01-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('content_type', models.CharField(choices=[('product', 'Товар'), ('news', 'Новость')], max_length=20, verbose_name='Тип контента')),
                ('image', models.ImageField(blank=True, null=True, upload_to='constructor_content/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('text', models.TextField(blank=True, verbose_name='Текст новости')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Элемент контента',
                'verbose_name_plural': 'Элементы контента',
            },
        ),
        migrations.CreateModel(
            name='PageDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('blocks', models.JSONField(default=list, verbose_name='Блоки конструктора')),
                ('text_color', models.CharField(default='#000000', max_length=7, verbose_name='Цвет текста')),
                ('bg_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет фона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Дизайн страницы',
                'verbose_name_plural': 'Дизайны страниц',
            },
        ),
    ]
