# Generated by Django 5.2.9 on 2026-01-11 13:32

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('content_type', models.CharField(choices=[('product', 'Товар'), ('news', 'Новость')], max_length=20, verbose_name='Тип контента')),
                ('image', models.ImageField(blank=True, null=True, upload_to='constructor_content/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('text', models.TextField(blank=True, verbose_name='Текст новости')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Элемент контента',
                'verbose_name_plural': 'Элементы контента',
                'db_table': 'construct_contentitem',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type'], name='construct_c_content_ef34d9_idx'), models.Index(fields=['is_active'], name='construct_c_is_acti_8df7bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Без названия', max_length=200, verbose_name='Название')),
                ('blocks', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Блоки конструктора')),
                ('text_color', models.CharField(default='#000000', max_length=7, verbose_name='Цвет текста')),
                ('bg_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет фона')),
                ('json_file', models.FileField(blank=True, null=True, upload_to='constructor_json/', verbose_name='JSON файл')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='Версия')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный доступ')),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Метаданные')),
                ('blocks_count', models.IntegerField(default=0, verbose_name='Количество блоков')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='constructor_thumbnails/', verbose_name='Превью')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Дизайн страницы',
                'verbose_name_plural': 'Дизайны страниц',
                'db_table': 'construct_pagedesign',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PageDesignHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, verbose_name='Версия')),
                ('blocks', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Блоки')),
                ('text_color', models.CharField(max_length=7, verbose_name='Цвет текста')),
                ('bg_color', models.CharField(max_length=7, verbose_name='Цвет фона')),
                ('change_comment', models.TextField(blank=True, verbose_name='Комментарий изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменено')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='construct.pagedesign', verbose_name='Дизайн')),
            ],
            options={
                'verbose_name': 'История дизайна',
                'verbose_name_plural': 'История дизайнов',
                'db_table': 'construct_pagedesign_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pagedesign',
            index=models.Index(fields=['user', 'created_at'], name='construct_p_user_id_be2dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='pagedesign',
            index=models.Index(fields=['is_public'], name='construct_p_is_publ_9b9c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='pagedesign',
            index=models.Index(fields=['name'], name='construct_p_name_d2b3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='pagedesignhistory',
            index=models.Index(fields=['design'], name='construct_p_design__8c4380_idx'),
        ),
        migrations.AddIndex(
            model_name='pagedesignhistory',
            index=models.Index(fields=['created_at'], name='construct_p_created_7c2359_idx'),
        ),
    ]
