# Generated by Django 5.2.9 on 2026-01-10 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagedesign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Дизайн страницы', 'verbose_name_plural': 'Дизайны страниц'},
        ),
        migrations.AddField(
            model_name='pagedesign',
            name='json_file',
            field=models.FileField(blank=True, null=True, upload_to='constructor_json/', verbose_name='JSON файл'),
        ),
        migrations.AddField(
            model_name='pagedesign',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
