# Generated by Django 5.2.9 on 2026-01-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False, 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
